server:
  port: 8080
spring:
  profiles:
    active: @profileActive@
  freemarker:
    template-loader-path:
    - classpath:/templates
    - file:./templates
    cache: false
    checkTemplateLocation: false
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  mail:
    host: smtp.yeah.com
    username: wangxuemingcn@yeah.net
    password: 12345
    port: 25
    properties:
      mail.smtp.auth: true

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.eussi.blog.modules.po
  mapperLocations: classpath:mapper/*.xml


# 注入给SiteOptions
# site.options.theme: [default|classic]
site:
    version: 1.0.0
    theme: default
    controls:
        register: true
        comment: true
    # 系统默认配置, 启动后 mto_options 的配置将覆盖此属性
    options:
        theme: default
        site_name: wangxueming's site
        site_keywords: blog
        site_metas:
        site_description: A freewheeling website
        storage_max_width: 800
        storage_limit_size: 2
